### ISSUE TITLE
Check form settings work correctly

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/kobo-api-app#2]
Currently survey and choice sheets swap json-xls formatting using first row for json keys (and vice versa). The settings page is formatted only as key-value pairs (no title row) so needs to be parsed/created differently

**Comment by chrismclarke** [comment]
should first check if we actually use settings before prioritising

**Comment by dave-mills** [comment]
I currently send a settings object in main form object to add project-specific form names. My understanding of the current setup is that all 3 worksheets require a similar format - basically 1 child object per row, with the header row being created from they keys. 

Not sure if we need to change it for the settings? I guess it would be more optimal, as we know the settings will only ever have 1 row after the header.

**Comment by chrismclarke** [comment]
Ok, I had it totally wrong, I thought that there were only ever two columns which matched key-value pairs (problem with testing with a 2x2 grid of data!). I can see from the spec that this is in fact false, so disregard.
http://xlsform.org/#settings

closing
